name: extractor

on: [push, pull_request]

jobs:
    extract:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x

            - name: npm install builder and run preparation
              run: |
                  cd builder 
                  npm install
                  node prepare.js

            - name: npm install project and run extractor
              run: |
                  npm install
                  npm run build
                  npm run extract

            - name: Archive extracted data
              uses: actions/upload-artifact@v4
              with:
                  name: extracted-data
                  path: ./out
